---
title: "Preliminary Analysis"
author: "Baishan Guo"
date: "8/15/2020"
output: html_document
---

```{r setup, include=FALSE, message=FALSE, warning=FALSE}
knitr::opts_chunk$set(echo = TRUE)

library(lubridate)
library(tidyverse)
library(TTR)
library(ggmap)
library(leaflet)

setwd("D:/Desktop/ppt")

source("code+data/code/simulator.R") # real data functions
source("code+data/code/est_infer_func.R") # real data functions
source("code+data/code/predictFunc2.R") # prediction functions (similar to kriging functions)
```

## Data Preprocessing

```{r, warning=FALSE}
# data preprocessing
dat <- read.csv("city_pol_h.csv", stringsAsFactors = F, sep = ";")
dat <- dat[1:500000,] %>%
  mutate(time = as.POSIXct(time), pm2_5 = as.numeric(pm2_5)) %>%
  select(station_code, time, pm2_5) %>%
  # abnormal values to NA
  mutate(pm2_5 = ifelse(pm2_5 < 0, NA, pm2_5)) %>%
  # one-year Beijing data from 2018.02 - 2019.02
  filter(as.Date(time) > '2018-01-31',
         as.Date(time) < '2019-02-01',
         substr(station_code, 1, 3) == 'G11')

# unique stations
stations <- unique(dat$station_code)

# missing timestamp
missing_tmp <- data.frame('station_code' = setdiff(stations, "G110001"),
                          'time' = as.POSIXct("2019-01-01 00:00:00"),
                          'pm2_5' = NA)

# remove station G110008 & G110009
dat <- rbind(dat, missing_tmp) %>%
  arrange(station_code, time)
dat %>% group_by(station_code) %>%
  summarise(count=n())
```

```{r}
# long table to wide table
dat_wide <- dat %>%
  filter(station_code != 'G110008', 
         station_code != 'G110009') %>%
  spread(key = station_code, value = pm2_5)

# impute the missing values
impute_missing <- function(x) { 
  if (sum(is.na(x))==0)
    return(x)
  ind <- which(is.na(x))
  indm <- cbind(ind-3, ind-2, ind-1, ind+1, ind+2, ind+3)
  indm[indm<1] <- 1
  Xmat <- cbind(x[indm[,1]], x[indm[,2]], x[indm[,3]], 
                x[indm[,4]], x[indm[,5]], x[indm[,6]])
  x[ind] <- apply(Xmat, 1, mean, na.rm = T)
  return(x)
}

# replace with the most recent none NA value
impute_missing2 <- function(x) { 
  if (sum(is.na(x))==0)
    return(x)
  ind <- which(is.na(x))
  values <- x[ind[c(1, which(diff(ind)> 1)+1)] - 1]
  len <- diff(c(1, which(diff(ind)> 1)+1, length(ind) + 1))
  x[ind] <- rep(values, len)
  return(x)
}

dat_wide2 <- apply(dat_wide[, -1], 2, impute_missing)
dat_wide2 <- apply(dat_wide2, 2, impute_missing)
dat_wide2 <- apply(dat_wide2, 2, impute_missing2)

#save(dat_wide2, file = "data_wide_new.rda")
dim(dat_wide2)
```

## Visualizations

```{r}
all_stations <- read.csv("station_location.csv")
stations_loc <- all_stations %>%
  filter(station_code %in% stations)
leaflet(stations_loc) %>% addTiles() %>%
  addCircleMarkers(lng=~lon, lat=~lat)
```

```{r, warnings=FALSE, message=FALSE}
new_dat <- dat_wide2 %>% 
  as.data.frame() %>%
  mutate(time = dat_wide$time) %>%
  gather(key = station, value = pm2_5, -time)

new_dat %>%
  group_by(time) %>%
  summarise(pm2_5 = mean(pm2_5, na.rm = T)) %>%
  mutate(pm2_5avg = as.numeric(SMA(ts(pm2_5), n=24))) %>%
  ggplot(aes(x = time, y = pm2_5avg)) +
    geom_line()+
    labs(x = '', 
         y = expression("Average PM2.5 ("~mu~"g/"~m^3~")"), 
         title = 'Beijing PM2.5 Hourly Concentrations, Moving Average with 24-hour-window') +
    theme_classic()
```

```{r}
new_dat %>%
  mutate(date = as.Date(time)) %>%
  group_by(date) %>%
  summarise(pm2_5 = mean(pm2_5, na.rm = T)) %>%
  ggplot(aes(x = date, y = pm2_5)) +
    geom_line()+
    labs(x = '', 
         y = expression("Average PM2.5 ("~mu~"g/"~m^3~")"), 
         title = 'Beijing PM2.5 Daily Concentrations') +
    theme_classic()
```

```{r}
new_dat %>%
  mutate(
    season = case_when(
      month(time) %in%  9:11 ~ "Fall",
      month(time) %in%  c(12, 1, 2)  ~ "Winter",
      month(time) %in%  3:5  ~ "Spring",
      TRUE ~ "Summer")
  ) %>%
  ggplot(aes(x = season, y = pm2_5)) +
    geom_boxplot() +
    labs(x = '', 
         y = expression("Average PM2.5 ("~mu~"g/"~m^3~")"), 
         title = 'Beijing PM2.5 Boxplot by Season, 2018.02-2019.02') +
    theme_classic()
```

```{r}
# 时间散点图
plot_dat <- new_dat %>% filter(station == 'G110002')

cbind(plot_dat$pm2_5[-1], plot_dat$pm2_5[-dim(plot_dat)[1]]) %>%
  as.data.frame() %>%
  ggplot(aes(x = V2, y = V1)) + 
    geom_point(size = 0.5) +
    theme_classic() +
    labs(x = expression(atop(PM[2.5]~ "at t-1" ~"("~mu~"g/"~m^3~")")), 
         y = expression(atop(PM[2.5]~" at t"~"("~mu~"g/"~m^3~")")),
         title = 'Dongsi Station, PM2.5 time t vs t-1, 2018.02-2019.02') 
```

```{r}
# 空间散点图
dat_nghbs <- new_dat %>% 
  filter(station %in% c('G110001', 'G110003', 'G110005', 'G110007')) %>%
  group_by(time) %>%
  summarise(pm2_5 = mean(pm2_5))

cbind(plot_dat$pm2_5[-1], dat_nghbs$pm2_5[-dim(dat_nghbs)[1]]) %>%
  as.data.frame() %>%
  ggplot(aes(x = V2, y = V1)) + 
    geom_point(size = 0.5) +
    theme_classic() +
    labs(x = expression(atop(PM[2.5]~" of neighbors at t-1"~"("~mu~"g/"~m^3~")")), 
         y = expression(atop(PM[2.5]~" of target station at t"~"("~mu~"g/"~m^3~")")),
         title = 'Dongsi Station, PM2.5 time t vs Spatial Neighbors at t-1') 
```

## Modeling

```{r}
Ymat <- log(t(dat_wide2 + 0.01))
pm_sma <- as.numeric(SMA(ts(colMeans(Ymat), start=c(1)), n=24))
Ymat_detrend <- t(apply(Ymat[,!is.na(pm_sma)], 1, 
                        function(x) x-pm_sma[!is.na(pm_sma)]))

#save(Ymat, Ymat_detrend, file = "Ymat.rda")
```

```{r}
#load("Ymat.rda")
dist_loc2 <- stations_loc %>%
  filter(station_code != 'G110008', 
         station_code != 'G110009') %>% 
  select(lon, lat) %>%
  dist() %>% as.matrix()

#Ymat0 <- Ymat
Ymat <- Ymat_detrend
#Ymat = Ymat0
Time <- ncol(Ymat)

### estimate rhos and mu
rhosMu <- estRhoMu(Ymat)
rhosMu
```

```{r}
show(mean(rhosMu[1,])/(1-mean(rhosMu[2,])))
model_name <- c("{\\sc Exponential}", "{\\sc Quadratic}")
cov.types <- c("exp", "quad")
lam <- 1

for (i in 1:2)
{
  if (i == 2)
  {
    cat(" & $\\mu$ & $\\phi_u$ & $\\alpha$ & $\\phi_x$ & $\\phi_e$ \\\\ \n")
    cat("\\hline \n")
  }
  cov.type = cov.types[i]
  
  ### for estimation theta_x
  (thetaMu = estThetaMu(rhosMu[1,], dist_loc2*lam, infer = T, p.value = T, cov.type = cov.type))
  (thetaX = estThetaRho(rhosMu[2,], dist_loc2*lam, infer = T, p.value = T, cov.type = cov.type))
  
  ### for estimation theta_e
  (thetaE = lse.theta(Ymat, dist_loc2*lam, rhos = rhosMu[2,], mu = rhosMu[1,], infer = T, p.value = T, cov.type = cov.type))
  
  ### output in latex format
  theta = c(thetaMu[[1]][1:2], thetaX[[1]][1:2], thetaE[[1]][1])
  theta_p = c(thetaMu[[4]][1:2], thetaX[[4]][1:2], thetaE[[4]][1])
  pv_c = specify_decimal(theta_p, 3)
  pv_c = paste0("(", pv_c, ")")
  pv_c[theta_p<0.001] = "($<0.001$)"
  
  est = specify_decimal(theta, 5)
  cat(model_name[i], "&", paste(est,  collapse = " & "), "\\\\ \n")
  cat("& ", paste(pv_c,  collapse = " & "), "\\\\ \n")
  cat("\\hline \n")
}
```

## Kriging

```{r hide, echo=FALSE}
predict.typeI<-function(Y_train, rhos_train, mus_train, dist_loc2, n_train,
                        n_pred, thetaE, thetaX, thetaMu, cov.type = "exp", 
                        Nrep = 10, mixed = F) {
  if (!mixed) {
    cov.type1 = cov.type
    cov.type2 = cov.type
  } else {
    cov.type1 = "exp"
    cov.type2 = "quad"
  }
    
  Time = ncol(Y_train)
  betaE = thetaE[1]; sig2E = thetaE[2]
  alpha = thetaX[1]; betaX = thetaX[2]; sig2X = thetaX[3]
  mu = thetaMu[1]; betaMu = thetaMu[2]; sig2Mu = thetaMu[3]
  N = dim(dist_loc2)[1]
  
  rhos_R = simu.rho.rep(beta = betaX, sig2 = sig2X, N, Nrep, alpha = alpha, 
                        dist_loc2, cov.type1)
  mus_R = simu.mu.rep(beta = betaMu, sig2 = sig2Mu, N, Nrep, mu = mu, 
                      dist_loc2, cov.type1)
  Y_R = simu.Y.rep(beta = betaE, sigy2 = sig2E, N, Nrep, Time, rhos_R, 
                   dist_loc2, mus_R, cov.type2)
  Y_R0 = Y_R - rowMeans(Y_R)
  rr = rep(1:Nrep, each = N)
  Y_R0_list = split.data.frame(Y_R0, factor(rr))
  SigY = Reduce("+", lapply(Y_R0_list, function(Y0) tcrossprod(Y0[1:n_train,])/Time))/Nrep
  if (n_train+1==N)
    cy0 = Reduce("+", lapply(Y_R0_list, function(Y0) colSums(Y0[(n_train+1):N,]*t(Y0[1:n_train,]))/Time))/Nrep
  else
    cy0 = Reduce("+", lapply(Y_R0_list, function(Y0) tcrossprod(Y0[1:n_train,], Y0[(n_train+1):N,])/Time))/Nrep
  
  muY = mean(Y_train[,Time])
  Yhat_train = mus_train + rhos_train*Y_train[,Time-1]
  Y_pred = t(cy0)%*%solve(SigY)%*%(Yhat_train - muY) + muY
  return(Y_pred)
}
```

```{r, eval=FALSE}
set.seed(2345)

# predictive kriging using sliding window 2500
begin_ind <- 1
est_win <- 4000
pred_win <- ncol(Ymat) - est_win
end_ind <- begin_ind + pred_win - 2

Yt_pred1 <- matrix(0, nrow = 1, ncol = pred_win)
Yt_pred2 <- matrix(0, nrow = 1, ncol = pred_win)
Ymat_sub <- matrix(0, nrow = 1, ncol = ncol(Ymat))
    
Time <- ncol(Ymat)

# location to be predicted
s_num <- 2

for (t in begin_ind:end_ind) {
  time_win <- t:(t + est_win)
  Ymat_win <- Ymat[, time_win]
  
  if (t %% 100 == 0) {
    cat(t, " | ")
  }
  
  dist_train <- dist_loc2[-s_num, -s_num]
  dist_pred  <- dist_loc2[-s_num, s_num, drop=FALSE]
  Y_train <- Ymat_win[-s_num, ]
  
  rhosMu <- estRhoMu(Y_train)
  mus_est <- rhosMu[1,]
  rhos_est <- rhosMu[2,]
  
  (thetaMu <- estThetaMu(mus_est, dist_train, infer = F,  cov.type = "exp"))
  (thetaX <- estThetaRho(rhos_est, dist_train, infer = F, cov.type = "exp"))
  (thetaE <- lse.theta(Y_train, dist_train, rhos = rhos_est, mu = mus_est, 
                      infer = F, cov.type = "exp"))
      
  Yt_pred2[, t] <- predict.typeII(Y_train, rhos_est, mus_est, 
                                              dist_train, as.vector(dist_pred), 
                                              thetaE, thetaX, thetaMu, 
                                              cov.type = "exp") 
  Yt_pred1[, t] <- predict.typeI(Y_train, rhos_est, mus_est, 
                                             dist_loc2, 10, 1,
                                             thetaE, thetaX, thetaMu, 
                                             cov.type = "exp")
  
  #ind1 <- 1:(t-begin_ind+1)
  #ind2 <- (Time-begin_ind+1):(Time-t+1)
  
  #cat("time win:")
  #pred1_rmse <- sqrt(mean((Yt_pred1[, ind1] - Ymat_sub[, ind2])^2))
  #pred2_rmse <- sqrt(mean((Yt_pred2[, ind1] - Ymat_sub[, ind2])^2))
  
  #muY <- mean(Ymat_sub[, ind2])
  #sse <- sqrt(mean((Ymat_sub[, ind2]- muY)^2))
  
  #cat("Time point: ", t, 
  #    " Pred RMSE: ", pred1_rmse, pred2_rmse, "\n",
  #    "Pred RMSE R2: ", 1- (pred1_rmse/sse)^2, 1- (pred2_rmse/sse)^2, "\n")
}
    
pred1_rmse <- sqrt(mean((Yt_pred1 - Ymat[s_num,(est_win+1):Time])^2))
pred2_rmse <- sqrt(mean((Yt_pred2 - Ymat[s_num,(est_win+1):Time])^2))
    
muY <- mean(Ymat[s_num,(est_win+1):Time])
sse <- sqrt(mean((Ymat[s_num,(est_win+1):Time] - muY)^2))
    
cat("BackPred Start Point: ", begin_ind, 
    "Est_win: ", est_win, 
    "Pred_win: ", pred_win, "\n",
    "Pred RMSE R2: ", 1- (pred1_rmse/sse)^2, 1- (pred2_rmse/sse)^2, "\n")
```

```{r, echo=FALSE}
cat("
  BackPred Start Point:  1 
  Est_win:  4000 
  Pred_win: 4736 
  Pred RMSE R2:  TYPE1: 0.521329  TYPE2: 0.4010529")
```

```{r, echo=FALSE}
#save(pred_data, file = 'pred.RData')
load("pred.RData")
```

```{r, eval=FALSE}
pred_data <- data.frame(type1=as.vector(Yt_pred1),
                        type2=as.vector(Yt_pred2),
                        true=Ymat[s_num,(est_win+1):Time],
                        date=dat_wide$time[(est_win+1):Time])
```

```{r}
pred_data[1000:1600,] %>%
  gather(key = Type, value = pm2_5, -date) %>%
  ggplot(aes(x = date, y = pm2_5, color = Type)) +
    geom_line() +
    scale_colour_manual(values=c("darkcyan","goldenrod4","cyan")) +
    labs(x = '', 
         y = "Detrended Log value of PM2.5", 
         title = 'Predicted Kriging') +
    ylim(-4, 2) + 
    theme_classic()
```


```{r, eval=FALSE, echo=FALSE}
set.seed(2345)

# predictive kriging using sliding window 2500
begin_ind <- 1
est_win <- 4000
pred_win <- ncol(Ymat) - est_win
end_ind <- begin_ind + pred_win - 1

Yt_pred1 <- matrix(0, nrow = 1, ncol = pred_win)
Yt_pred2 <- matrix(0, nrow = 1, ncol = pred_win)
Ymat_sub <- matrix(0, nrow = 1, ncol = ncol(Ymat))
    
Time <- ncol(Ymat)

# location to be predicted
s_num <- 2

for (t in begin_ind:end_ind) {
  time_win <- (Time - t - est_win + 1):(Time - t + 1)
  Ymat_win <- Ymat[, time_win]
  
  if (t %% 100 == 0) {
    cat(t, " | ")
  }
  
  dist_train <- dist_loc2[-s_num, -s_num]
  dist_pred  <- dist_loc2[-s_num, s_num, drop=FALSE]
  Y_train <- Ymat_win[-s_num, ]
  
  rhosMu <- estRhoMu(Y_train)
  mus_est <- rhosMu[1,]
  rhos_est <- rhosMu[2,]
  
  (thetaMu <- estThetaMu(mus_est, dist_train, infer = F,  cov.type = "exp"))
  (thetaX <- estThetaRho(rhos_est, dist_train, infer = F, cov.type = "exp"))
  (thetaE <- lse.theta(Y_train, dist_train, rhos = rhos_est, mu = mus_est, 
                      infer = F, cov.type = "exp"))
      
      
  Ymat_sub[, Time - t + 1] <- Ymat[s_num, Time - t + 1]
  Yt_pred2[, t-begin_ind+1] <- predict.typeII(Y_train, rhos_est, mus_est, 
                                              dist_train, as.vector(dist_pred), 
                                              thetaE, thetaX, thetaMu, 
                                              cov.type = "exp") 
  Yt_pred1[, t-begin_ind+1] <- predict.typeI(Y_train, rhos_est, mus_est, 
                                             dist_loc2, 10, 1,
                                             thetaE, thetaX, thetaMu, 
                                             cov.type = "exp")
  
  #ind1 <- 1:(t-begin_ind+1)
  #ind2 <- (Time-begin_ind+1):(Time-t+1)
  
  #cat("time win:")
  #pred1_rmse <- sqrt(mean((Yt_pred1[, ind1] - Ymat_sub[, ind2])^2))
  #pred2_rmse <- sqrt(mean((Yt_pred2[, ind1] - Ymat_sub[, ind2])^2))
  
  #muY <- mean(Ymat_sub[, ind2])
  #sse <- sqrt(mean((Ymat_sub[, ind2]- muY)^2))
  
  #cat("Time point: ", t, 
  #    " Pred RMSE: ", pred1_rmse, pred2_rmse, "\n",
  #    "Pred RMSE R2: ", 1- (pred1_rmse/sse)^2, 1- (pred2_rmse/sse)^2, "\n")
}
    
pred1_rmse <- sqrt(mean((Yt_pred1 - Ymat_sub[,(Time -begin_ind+1):(Time -begin_ind+1 - pred_win +1)])^2))
pred2_rmse <- sqrt(mean((Yt_pred2 - Ymat_sub[,(Time -begin_ind+1):(Time -begin_ind+1 - pred_win +1)])^2))
    
muY <- mean(Ymat_sub[,(Time -begin_ind+1):(Time -begin_ind+1 - pred_win +1)])
sse <- sqrt(mean((Ymat_sub[,(Time -begin_ind+1):(Time -begin_ind+1 - pred_win +1)]- muY)^2))
    
cat("BackPred Start Point: ", begin_ind, 
    "Est_win: ", est_win, 
    "Pred_win: ", pred_win, "\n",
    "Pred RMSE R2: ", 1- (pred1_rmse/sse)^2, 1- (pred2_rmse/sse)^2, "\n")
```
